swagger: "2.0"
info:
  description: "This is a sample server Guesser server."
  version: "1.0.0"
  title: "Randomizer"
  termsOfService: "http://guesser.io/terms/"
  contact:
    email: "apiteam@guesser.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8081"
basePath: "/v2"
tags:
- name: "guess"
  description: "All good guesses count"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
schemes:
- "http"
paths:
  /randomize:
    get:
      tags:
      - "randomize"
      summary: "Health point"
      description: "All generated responses returned."
      operationId: "health"
      consumes:
      - "*/*"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Health"
        400:
          description: "Invalid status value"
  /randomize/allPhrases:
    get:
      tags:
      - "phrase"
      summary: "Finds All Phrases"
      description: "All generated responses returned."
      operationId: "allPhrases"
      consumes:
      - "*/*"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Phrase"
        400:
          description: "Invalid status value"
definitions:
  Health:
    type: "object"
    properties:
      health:
        type: "string"
    xml:
      name: "Health"
  Phrase:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      guessedPhrase:
        type: "string"
      responsePhrase:
        type: "string"
      guessDate:
        type: "string"
        format: "date-time"
      guessed:
        type: "boolean"
        default: false
    xml:
      name: "Phrase"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
