/*
 * Randomizer
 * This is a sample server Guesser server.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@guesser.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.pivotal.microsamples.randomizer.auth;

public enum OAuthFlow {
    accessCode, implicit, password, application
}
